# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20170422_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Date_Naissance',
            field=models.DateField(blank=True),
        ),
    ]
