# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20170608_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_obs',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
