# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20170608_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_dosage', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('presc_time', models.DateTimeField(auto_now_add=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Drug')),
            ],
        ),
    ]
